import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    // Safelist para preservar classes usadas dinamicamente via JavaScript
    safelist: [
        // Classes de visibilidade
        'hidden',
        'block',
        'inline',
        'inline-block',
        'flex',
        'inline-flex',
        'grid',
        
        // Classes de estado (usadas em JavaScript)
        'opacity-0',
        'opacity-25',
        'opacity-50',
        'opacity-75',
        'opacity-100',
        
        // Classes de pointer events
        'pointer-events-none',
        'pointer-events-auto',
        
        // Classes de cores de fundo dinâmicas
        'bg-gray-50',
        'bg-gray-100',
        'bg-gray-200',
        'bg-gray-300',
        'bg-gray-400',
        'bg-gray-500',
        'bg-gray-600',
        'bg-gray-700',
        'bg-gray-800',
        'bg-gray-900',
        'bg-blue-50',
        'bg-blue-100',
        'bg-blue-200',
        'bg-blue-300',
        'bg-blue-400',
        'bg-blue-500',
        'bg-blue-600',
        'bg-blue-700',
        'bg-blue-800',
        'bg-blue-900',
        'bg-green-50',
        'bg-green-100',
        'bg-green-200',
        'bg-green-300',
        'bg-green-400',
        'bg-green-500',
        'bg-green-600',
        'bg-green-700',
        'bg-green-800',
        'bg-green-900',
        'bg-red-50',
        'bg-red-100',
        'bg-red-200',
        'bg-red-300',
        'bg-red-400',
        'bg-red-500',
        'bg-red-600',
        'bg-red-700',
        'bg-red-800',
        'bg-red-900',
        'bg-yellow-50',
        'bg-yellow-100',
        'bg-yellow-200',
        'bg-yellow-300',
        'bg-yellow-400',
        'bg-yellow-500',
        'bg-yellow-600',
        'bg-yellow-700',
        'bg-yellow-800',
        'bg-yellow-900',
        'bg-indigo-50',
        'bg-indigo-100',
        'bg-indigo-200',
        'bg-indigo-300',
        'bg-indigo-400',
        'bg-indigo-500',
        'bg-indigo-600',
        'bg-indigo-700',
        'bg-indigo-800',
        'bg-indigo-900',
        
        // Classes de texto dinâmicas
        'text-gray-50',
        'text-gray-100',
        'text-gray-200',
        'text-gray-300',
        'text-gray-400',
        'text-gray-500',
        'text-gray-600',
        'text-gray-700',
        'text-gray-800',
        'text-gray-900',
        'text-blue-50',
        'text-blue-100',
        'text-blue-200',
        'text-blue-300',
        'text-blue-400',
        'text-blue-500',
        'text-blue-600',
        'text-blue-700',
        'text-blue-800',
        'text-blue-900',
        'text-green-50',
        'text-green-100',
        'text-green-200',
        'text-green-300',
        'text-green-400',
        'text-green-500',
        'text-green-600',
        'text-green-700',
        'text-green-800',
        'text-green-900',
        'text-red-50',
        'text-red-100',
        'text-red-200',
        'text-red-300',
        'text-red-400',
        'text-red-500',
        'text-red-600',
        'text-red-700',
        'text-red-800',
        'text-red-900',
        'text-yellow-50',
        'text-yellow-100',
        'text-yellow-200',
        'text-yellow-300',
        'text-yellow-400',
        'text-yellow-500',
        'text-yellow-600',
        'text-yellow-700',
        'text-yellow-800',
        'text-yellow-900',
        'text-indigo-50',
        'text-indigo-100',
        'text-indigo-200',
        'text-indigo-300',
        'text-indigo-400',
        'text-indigo-500',
        'text-indigo-600',
        'text-indigo-700',
        'text-indigo-800',
        'text-indigo-900',
        
        // Classes de borda dinâmicas
        'border-gray-50',
        'border-gray-100',
        'border-gray-200',
        'border-gray-300',
        'border-gray-400',
        'border-gray-500',
        'border-gray-600',
        'border-gray-700',
        'border-gray-800',
        'border-gray-900',
        'border-blue-50',
        'border-blue-100',
        'border-blue-200',
        'border-blue-300',
        'border-blue-400',
        'border-blue-500',
        'border-blue-600',
        'border-blue-700',
        'border-blue-800',
        'border-blue-900',
        'border-green-50',
        'border-green-100',
        'border-green-200',
        'border-green-300',
        'border-green-400',
        'border-green-500',
        'border-green-600',
        'border-green-700',
        'border-green-800',
        'border-green-900',
        'border-red-50',
        'border-red-100',
        'border-red-200',
        'border-red-300',
        'border-red-400',
        'border-red-500',
        'border-red-600',
        'border-red-700',
        'border-red-800',
        'border-red-900',
        'border-yellow-50',
        'border-yellow-100',
        'border-yellow-200',
        'border-yellow-300',
        'border-yellow-400',
        'border-yellow-500',
        'border-yellow-600',
        'border-yellow-700',
        'border-yellow-800',
        'border-yellow-900',
        'border-indigo-50',
        'border-indigo-100',
        'border-indigo-200',
        'border-indigo-300',
        'border-indigo-400',
        'border-indigo-500',
        'border-indigo-600',
        'border-indigo-700',
        'border-indigo-800',
        'border-indigo-900',
        
        // Classes de ring (usadas em foco/seleção)
        'ring-2',
        'ring-blue-500',
        'ring-green-500',
        'ring-red-500',
        'ring-yellow-500',
        'ring-indigo-500',
        'ring-gray-500',
        
        // Classes de scale (usadas em animações)
        'scale-95',
        'scale-100',
        'scale-105',
        'scale-110',
        
        // Classes de gradiente (usadas dinamicamente)
        'bg-gradient-to-br',
        'from-gray-700',
        'to-gray-800',
        'from-gray-600',
        'to-gray-700',
        'from-blue-600',
        'to-blue-700',
        'from-blue-700',
        'to-blue-800',
        'from-yellow-400',
        'to-yellow-500',
        'from-green-600',
        'to-green-700',
        'from-red-600',
        'to-red-700',
        'from-indigo-600',
        'to-indigo-700',
        
        // Classes dark mode dinâmicas
        'dark:bg-gray-700',
        'dark:bg-gray-800',
        'dark:bg-gray-900',
        'dark:bg-blue-600',
        'dark:bg-blue-700',
        'dark:bg-blue-800',
        'dark:bg-blue-900',
        'dark:bg-green-600',
        'dark:bg-green-700',
        'dark:bg-green-800',
        'dark:bg-green-900',
        'dark:bg-red-600',
        'dark:bg-red-700',
        'dark:bg-red-800',
        'dark:bg-red-900',
        'dark:bg-yellow-600',
        'dark:bg-yellow-700',
        'dark:bg-yellow-800',
        'dark:bg-yellow-900',
        'dark:bg-orange-600',
        'dark:bg-orange-700',
        'dark:bg-orange-800',
        'dark:bg-orange-900',
        'dark:bg-indigo-600',
        'dark:bg-indigo-700',
        'dark:bg-indigo-800',
        'dark:bg-indigo-900',
        'dark:text-gray-100',
        'dark:text-gray-200',
        'dark:text-gray-300',
        'dark:text-gray-400',
        'dark:text-blue-300',
        'dark:text-blue-400',
        'dark:text-green-300',
        'dark:text-green-400',
        'dark:text-red-300',
        'dark:text-red-400',
        'dark:text-yellow-300',
        'dark:text-yellow-400',
        'dark:text-orange-300',
        'dark:text-orange-400',
        'dark:text-indigo-300',
        'dark:text-indigo-400',
        'dark:border-gray-600',
        'dark:border-gray-700',
        'dark:border-blue-600',
        'dark:border-blue-700',
        'dark:border-green-600',
        'dark:border-green-700',
        'dark:border-red-600',
        'dark:border-red-700',
        'dark:border-yellow-600',
        'dark:border-yellow-700',
        'dark:border-orange-600',
        'dark:border-orange-700',
        'dark:border-indigo-600',
        'dark:border-indigo-700',
        
        // Classes específicas para status dinâmicos
        'bg-yellow-50',
        'bg-orange-50',
        'bg-orange-100',
        'bg-orange-200',
        'bg-orange-300',
        'bg-orange-400',
        'bg-orange-500',
        'bg-orange-600',
        'bg-orange-700',
        'bg-orange-800',
        'bg-orange-900',
        'text-orange-50',
        'text-orange-100',
        'text-orange-200',
        'text-orange-300',
        'text-orange-400',
        'text-orange-500',
        'text-orange-600',
        'text-orange-700',
        'text-orange-800',
        'text-orange-900',
        'border-orange-50',
        'border-orange-100',
        'border-orange-200',
        'border-orange-300',
        'border-orange-400',
        'border-orange-500',
        'border-orange-600',
        'border-orange-700',
        'border-orange-800',
        'border-orange-900',
        'dark:bg-yellow-900/20',
        'dark:bg-green-900/20',
        'dark:bg-red-900/20',
        'dark:bg-orange-900/20',
        'dark:border-yellow-700',
        'dark:border-green-700',
        'dark:border-red-700',
        'dark:border-orange-700',
        'dark:text-yellow-200',
        'dark:text-yellow-300',
        'dark:text-green-200',
        'dark:text-green-300',
        'dark:text-red-200',
        'dark:text-red-300',
        'dark:text-orange-200',
        'dark:text-orange-300',
        
        // Classes de notificação dinâmica
        'bg-green-600',
        'bg-red-600',
        'bg-yellow-600',
        'bg-blue-600',
        
        // Classes de layout dinâmico
        'rounded-lg',
        'p-4',
        'px-6',
        'py-3',
        'shadow-lg',
        'font-medium',
        'text-white',
        'fixed',
        'top-4',
        'right-4',
        'z-50',
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Figtree', ...defaultTheme.fontFamily.sans],
            },
        },
    },

    plugins: [forms],
};
